// Generated by CodiumAI

import { BadRequestException, UnauthorizedException } from '@nestjs/common';
import { Test, TestingModule } from '@nestjs/testing';
import { getRepositoryToken } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { CreateUserDto } from '@api/users/dto/create-user.dto';
import { User } from '@api/users/entities/user.entity';
import { UsersService } from '@api/users/users.service';

import { AuthService } from './auth.service';
import { LoginDto } from './dto/login.dto';

describe('AuthService', () => {
  let authService: AuthService;
  let userRepository: Repository<User>;
  const user: User = {
    checkPassword: () => Promise.resolve(true),
    delete_date: new Date(),
    email: 'jhon@doe.com',
    id: 1,
    password: 'password',
    username: 'jhonDoe',
  };

  const testEmail = 'jhon@doe.com';

  const mockRepository: object = {
    save: jest.fn(() => user),
    create: jest.fn(),
    find: jest.fn(() => []),
    findOneBy: jest.fn(),
    update: jest.fn(),
    softDelete: jest.fn(),
  };
  const USER_REPOSITORY_TOKEN = getRepositoryToken(User);
  jest
    .spyOn(userRepository, 'findOneBy')
    .mockImplementationOnce(async () => user);

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        UsersService,
        {
          provide: USER_REPOSITORY_TOKEN,
          useValue: mockRepository,
        },
      ],
    }).compile();

    authService = module.get<AuthService>(UsersService);
    userRepository = module.get<Repository<User>>(USER_REPOSITORY_TOKEN);
  });

  it('should register a new user and login successfully', async () => {
    const createUserDto = new CreateUserDto();
    createUserDto.username = 'john doe';
    createUserDto.email = testEmail;
    createUserDto.password = 'password123';
    createUserDto.validatePassword = 'password123';

    const result = await authService.register(createUserDto);
    expect(result).toHaveProperty('token');

    const loginDto = new LoginDto();
    loginDto.email = testEmail;
    loginDto.password = 'password123';

    const loginResult = await authService.login(loginDto);
    expect(loginResult).toHaveProperty('token');
  });

  // Login with valid credentials, expecting a valid token to be returned.
  it('should login with valid credentials', async () => {
    const loginDto = new LoginDto();
    loginDto.email = testEmail;
    loginDto.password = 'password123';

    const result = await authService.login(loginDto);
    expect(result).toHaveProperty('token');
  });

  // Login with invalid email, expecting an UnauthorizedException to be thrown.
  it('should throw UnauthorizedException when login with invalid email', async () => {
    const loginDto = new LoginDto();
    loginDto.email = 'invalid@example.com';
    loginDto.password = 'password123';

    await expect(authService.login(loginDto)).rejects.toThrow(
      UnauthorizedException,
    );
  });

  // Register a new user with invalid email, expecting a BadRequestException to be thrown.
  it('should throw BadRequestException when register with invalid email', async () => {
    const createUserDto = new CreateUserDto();
    createUserDto.username = 'john doe';
    createUserDto.email = 'invalidemail';
    createUserDto.password = 'password123';
    createUserDto.validatePassword = 'password123';

    await expect(authService.register(createUserDto)).rejects.toThrow(
      BadRequestException,
    );
  });

  // Register a new user with invalid password, expecting a BadRequestException to be thrown.
  it('should throw BadRequestException when register with invalid password', async () => {
    const createUserDto = new CreateUserDto();
    createUserDto.username = 'john doe';
    createUserDto.email = testEmail;
    createUserDto.password = 'pass';
    createUserDto.validatePassword = 'pass';

    await expect(authService.register(createUserDto)).rejects.toThrow(
      BadRequestException,
    );
  });

  // Login with empty email, expecting a BadRequestException to be thrown.
  it('should throw BadRequestException when login with empty email', async () => {
    const loginDto = new LoginDto();
    loginDto.email = '';
    loginDto.password = 'password123';

    await expect(authService.login(loginDto)).rejects.toThrow(
      BadRequestException,
    );
  });
});
